name: Validate data file
on: [ push, pull_request ]
jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Compile scripts
        run: |
          npm ci
          npm run build
          npm exec strip-json-comments-cli data/mods.jsonc > compiled/mods.json
          npm exec strip-json-comments-cli data/broken-content-packs.jsonc > compiled/broken-content-packs.json

      - name: Validate JSON schema (mods)
        run: |
          node compiled/validate-json-schema.js data/schema.json compiled/mods.json

      - name: Validate JSON schema (broken content packs)
        run: |
          node compiled/validate-json-schema.js data/schema.json compiled/broken-content-packs.json

      - name: Validate data
        run: |
          node compiled/validate-mod-data.js compiled/mods.json compiled/broken-content-packs.json
